// Login
export const LoginData = {
  en: {
    welcomeBack: "Welcome back",
    loginText: "Login to your LMS account",
    identifierLabel: "Email, Username, or Phone",
    identifierPlaceholder: "Enter your email, username, or phone",
    passwordLabel: "Password",
    forgotPassword: "Forgot your password?",
    stayLoggedIn: "Stay logged in",
    signIn: "Sign In",
    orContinueWith: "Or continue with",
    loginWithGoogle: "Login with Google",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
  },
  ar: {
    welcomeBack: "مرحبًا بعودتك",
    loginText: "قم بتسجيل الدخول إلى حسابك في LMS",
    identifierLabel: "البريد الإلكتروني أو اسم المستخدم أو الهاتف",
    identifierPlaceholder:
      "أدخل بريدك الإلكتروني أو اسم المستخدم أو رقم الهاتف",
    passwordLabel: "كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    stayLoggedIn: "البقاء متصلاً",
    signIn: "تسجيل الدخول",
    orContinueWith: "أو تابع باستخدام",
    loginWithGoogle: "تسجيل الدخول باستخدام Google",
    noAccount: "ليس لديك حساب؟",
    signUp: "سجل",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
  },
  fr: {
    welcomeBack: "Content de vous revoir",
    loginText: "Connectez-vous à votre compte LMS",
    identifierLabel: "Email, Nom d'utilisateur ou Téléphone",
    identifierPlaceholder: "Entrez votre email, nom d'utilisateur ou téléphone",
    passwordLabel: "Mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    stayLoggedIn: "Rester connecté",
    signIn: "Se connecter",
    orContinueWith: "Ou continuez avec",
    loginWithGoogle: "Se connecter avec Google",
    noAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    termsOfService: "Conditions d'utilisation",
    privacyPolicy: "Politique de confidentialité",
  },
};

// Register
export const RegisterData = {
  en: {
    createAccount: "Create an account",
    signUp: "Sign up for your LMS account",
    name: "Name*",
    email: "Email*",
    password: "Password*",
    confirmPassword: "Confirm Password*",
    username: "Username",
    phone: "Phone",
    signUpButton: "Sign Up",
    orContinueWith: "Or continue with",
    loginWithGoogle: "Login with Google",
    alreadyHaveAccount: "Already have an account?",
    logIn: "Log in",
    termsAndConditions: "Terms of Service",
    privacyPolicy: "Privacy Policy",
  },
  ar: {
    createAccount: "إنشاء حساب",
    signUp: "اشترك في حساب LMS الخاص بك",
    name: "الاسم*",
    email: "البريد الإلكتروني*",
    password: "كلمة المرور*",
    confirmPassword: "تأكيد كلمة المرور*",
    username: "اسم المستخدم",
    phone: "الهاتف",
    signUpButton: "سجل",
    orContinueWith: "أو تابع باستخدام",
    loginWithGoogle: "تسجيل الدخول باستخدام Google",
    alreadyHaveAccount: "هل لديك حساب بالفعل؟",
    logIn: "تسجيل الدخول",
    termsAndConditions: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
  },
  fr: {
    createAccount: "Créer un compte",
    signUp: "Inscrivez-vous pour votre compte LMS",
    name: "Nom*",
    email: "E-mail*",
    password: "Mot de passe*",
    confirmPassword: "Confirmer le mot de passe*",
    username: "Nom d'utilisateur",
    phone: "Téléphone",
    signUpButton: "S'inscrire",
    orContinueWith: "Ou continuez avec",
    loginWithGoogle: "Se connecter avec Google",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    logIn: "Se connecter",
    termsAndConditions: "Conditions d'utilisation",
    privacyPolicy: "Politique de confidentialité",
  },
};

// ForgetPassword
export const ForgetPasswordData = {
  en: {
    title: "Forgot Password",
    subtitle: "Enter your email to reset your password",
    emailLabel: "Email",
    emailPlaceholder: "m@example.com",
    resetButton: "Reset Password",
    rememberPassword: "Remember your password?",
    backToLogin: "Back to Login",
  },
  fr: {
    title: "Mot de passe oublié",
    subtitle: "Entrez votre email pour réinitialiser votre mot de passe",
    emailLabel: "E-mail",
    emailPlaceholder: "m@exemple.com",
    resetButton: "Réinitialiser le mot de passe",
    rememberPassword: "Vous vous souvenez de votre mot de passe ?",
    backToLogin: "Retour à la connexion",
  },
  ar: {
    title: "نسيت كلمة المرور",
    subtitle: "أدخل بريدك الإلكتروني لإعادة تعيين كلمة المرور",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "m@example.com",
    resetButton: "إعادة تعيين كلمة المرور",
    rememberPassword: "هل تذكر كلمة المرور؟",
    backToLogin: "العودة إلى تسجيل الدخول",
  },
};

// ResetPassword
export const ResetPasswordData = {
  en: {
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm New Password",
    newPasswordPlaceholder: "Enter your new password",
    confirmPasswordPlaceholder: "Confirm your new password",
    resetPasswordButton: "Reset Password",
  },
  fr: {
    newPasswordLabel: "Nouveau mot de passe",
    confirmPasswordLabel: "Confirmer le nouveau mot de passe",
    newPasswordPlaceholder: "Entrez votre nouveau mot de passe",
    confirmPasswordPlaceholder: "Confirmez votre nouveau mot de passe",
    resetPasswordButton: "Réinitialiser le mot de passe",
  },
  ar: {
    newPasswordLabel: "كلمة المرور الجديدة",
    confirmPasswordLabel: "تأكيد كلمة المرور الجديدة",
    newPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
    confirmPasswordPlaceholder: "تأكيد كلمة المرور الجديدة",
    resetPasswordButton: "إعادة تعيين كلمة المرور",
  },
};

// CheckCode
export const CheckCodeData = {
  en: {
    title: "Reset Your Password",
    subtitleCodeSuccess: "Enter your new password",
    subtitleEnterCode: "Enter the code you received",
    resendCode: "Resend Code",
    submitCode: "Submit Code",
  },
  fr: {
    title: "Réinitialiser votre mot de passe",
    subtitleCodeSuccess: "Entrez votre nouveau mot de passe",
    subtitleEnterCode: "Entrez le code que vous avez reçu",
    resendCode: "Renvoyer le code",
    submitCode: "Soumettre le code",
  },
  ar: {
    title: "إعادة تعيين كلمة المرور",
    subtitleCodeSuccess: "أدخل كلمة المرور الجديدة الخاصة بك",
    subtitleEnterCode: "أدخل الرمز الذي تلقيته",
    resendCode: "إعادة إرسال الرمز",
    submitCode: "إرسال الرمز",
  },
};

// Header
export const HeaderData = {
  en: {
    academyName: "Naser Academy",
    register: "Register",
    login: "Login",
  },
  ar: {
    academyName: "أكاديمية ناصر",
    register: "تسجيل",
    login: "تسجيل الدخول",
  },
  fr: {
    academyName: "Académie Naser",
    register: "S'inscrire",
    login: "Se connecter",
  },
};

// Sidebar
export const SidebarData = {
  en: {
    logoName: "Ali Academy",
    dashboard: "Dashboard",
    myCourses: "My Courses",
    coursesWatched: "Courses I watched",
    completedCourses: "Completed courses",
    currentCourses: "My current courses",
    myLectures: "My Lectures",
    schedule: "Schedule",
    community: "Community",
    invoices: "Invoices",
    past: "Past",
    current: "Current",
    upcoming: "Upcoming",
    settings: "Settings",
    logout: "Logout",
  },
  ar: {
    logoName: "أكاديمية علي",
    dashboard: "لوحة التحكم",
    myCourses: "دوراتي",
    coursesWatched: "الدورات التي شاهدتها",
    completedCourses: "الدورات المكتملة",
    currentCourses: "دوراتي الحالية",
    myLectures: "محاضراتي",
    schedule: "الجدول",
    community: "المجتمع",
    invoices: "الفواتير",
    past: "الماضية",
    current: "الحالية",
    upcoming: "القادمة",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
  },
  fr: {
    logoName: "Académie Ali",
    dashboard: "Tableau de bord",
    myCourses: "Mes cours",
    coursesWatched: "Cours que j'ai regardés",
    completedCourses: "Cours terminés",
    currentCourses: "Mes cours en cours",
    myLectures: "Mes conférences",
    schedule: "Emploi du temps",
    community: "Communauté",
    invoices: "Factures",
    past: "Passé",
    current: "Actuel",
    upcoming: "À venir",
    settings: "Paramètres",
    logout: "Déconnexion",
  },
};

// Dashboard
export const DashboardData = {
  en: {
    dailyLessons: "Daily lessons",
    showMoreLessons: "Show more lessons",
    duration: "Duration",
    instructor: "Instructor",
    time: "Time",
    registeredCourses: "Registered courses",
    showMoreCourses: "Show more courses",
    residual: "Residual",
    rateTheLessons: "Rate The Lessons",
    academicAssignment: "Academic assignment",
    received: "Received",
    availableSoon: "Available soon",
    dailySchedule: "Daily schedule",
    tests: "Tests",
    showMoreTests: "Show more tests",
    invoices: "Invoices",
    today: "Today",
    yesterday: "Yesterday",
    tomorrow: "Tomorrow",
    amountDue: "Amount due",
    paymentNotMade: "Payment has not been made yet",
  },
  ar: {
    dailyLessons: "الدروس اليومية",
    showMoreLessons: "عرض المزيد من الدروس",
    duration: "المدة",
    instructor: "مدرب",
    time: "الوقت",
    registeredCourses: "الدورات المسجلة",
    showMoreCourses: "عرض المزيد من الدورات",
    residual: "المتبقي",
    rateTheLessons: "قيم الدروس",
    academicAssignment: "التكليف الأكاديمي",
    received: "تم الاستلام",
    availableSoon: "قريبا",
    dailySchedule: "الجدول اليومي",
    tests: "الاختبارات",
    showMoreTests: "عرض المزيد من الاختبارات",
    invoices: "الفواتير",
    today: "اليوم",
    yesterday: "أمس",
    tomorrow: "غداً",
    amountDue: "المبلغ المستحق",
    paymentNotMade: "لم يتم الدفع بعد",
  },
  fr: {
    dailyLessons: "Leçons quotidiennes",
    showMoreLessons: "Voir plus de leçons",
    duration: "Durée",
    instructor: "Instructeur",
    time: "Heure",
    registeredCourses: "Cours inscrits",
    showMoreCourses: "Voir plus de cours",
    residual: "Résiduel",
    rateTheLessons: "Évaluez les leçons",
    academicAssignment: "Devoir académique",
    received: "Reçu",
    availableSoon: "Disponible bientôt",
    dailySchedule: "Emploi du temps quotidien",
    tests: "Tests",
    showMoreTests: "Voir plus de tests",
    invoices: "Factures",
    today: "Aujourd'hui",
    yesterday: "Hier",
    tomorrow: "Demain",
    amountDue: "Montant dû",
    paymentNotMade: "Le paiement n'a pas encore été effectué",
  },
};

// Courses
export const CoursesData = {
  en: {
    coursesWatched: "Courses I watched",
    completedCourses: "Completed courses",
    currentCourses: "My current courses",
    sortBy: "Sort by",
    latest: "Latest",
    rating: "Rating",
    price: "Price",
    showLess: "Show less",
    showMore: "Show more",
    registerNow: "Register now",
    completed: "Completed",
    continueWatching: "Continue watching",
  },
  ar: {
    coursesWatched: "الدورات التي شاهدتها",
    completedCourses: "الدورات المكتملة",
    currentCourses: "دوراتي الحالية",
    sortBy: "فرز حسب",
    latest: "الأحدث",
    rating: "التقييم",
    price: "السعر",
    showLess: "عرض أقل",
    showMore: "عرض المزيد",
    registerNow: "سجل الآن",
    completed: "مكتمل",
    continueWatching: "متابعة المشاهدة",
  },
  fr: {
    coursesWatched: "Cours que j'ai regardés",
    completedCourses: "Cours terminés",
    currentCourses: "Mes cours en cours",
    sortBy: "Trier par",
    latest: "Dernier",
    rating: "Note",
    price: "Prix",
    showLess: "Afficher moins",
    showMore: "Afficher plus",
    registerNow: "Inscrivez-vous maintenant",
    completed: "Terminé",
    continueWatching: "Continuer à regarder",
  },
};

// Settings
export const SettingsData = {
  en: {
    myProfile: "My Profile",
    save: "Save",
    edit: "Edit",
    personalInfo: "Personal Information",
    educationalStage: "Educational Stage",
    institute: "Institute",
    number: "Number",
    email: "Email Address",
    aboutMe: "About Me",
    currentTime: "Current Time",
    subjects: "Subjects",
    certificates: "Certificates and Achievements",
    degree: "Degree",
    viewCertificate: "View Certificate",
    previousProjects: "Previous Projects and Works",
    viewProject: "View Project",
    reviews: "Reviews and Comments",
    viewAllReviews: "View All Reviews",
  },
  ar: {
    myProfile: "ملفي الشخصي",
    save: "حفظ",
    edit: "تعديل",
    personalInfo: "المعلومات الشخصية",
    educationalStage: "المرحلة الدراسية",
    institute: "المعهد",
    number: "الرقم",
    email: "البريد الإلكتروني",
    aboutMe: "نبذة عني",
    currentTime: "التوقيت الحالي",
    subjects: "المواد الدراسية",
    certificates: "الشهادات والإنجازات",
    degree: "الدرجة العلمية",
    viewCertificate: "عرض الشهادة",
    previousProjects: "المشاريع والأعمال السابقة",
    viewProject: "عرض المشروع",
    reviews: "المراجعات والتعليقات",
    viewAllReviews: "عرض جميع المراجعات",
  },
  fr: {
    myProfile: "Mon Profil",
    save: "Enregistrer",
    edit: "Modifier",
    personalInfo: "Informations personnelles",
    educationalStage: "Niveau scolaire",
    institute: "Institut",
    number: "Numéro",
    email: "Adresse e-mail",
    aboutMe: "À propos de moi",
    currentTime: "Heure actuelle",
    subjects: "Matières",
    certificates: "Certificats et réalisations",
    degree: "Diplôme",
    viewCertificate: "Voir le certificat",
    previousProjects: "Projets et travaux précédents",
    viewProject: "Voir le projet",
    reviews: "Avis et commentaires",
    viewAllReviews: "Voir tous les avis",
  },
};
