import React, { useEffect, useState } from "react";
import Projects from "../Components/Dashboard/Projects";
import { Loader, Projector } from "lucide-react";
import { ErrorMessage, presentationAPI } from "../../../lib/api";
import { toast } from "sonner";

export default function Shared() {
  const [loadingShared, setLoadingShared] = useState(true);
  const [allShared, setAllShared] = useState([]);

  const fetchShared = async () => {
    try {
      const { data } = await presentationAPI.getShared();
      setAllShared(data.data);
    } catch (error) {
      toast("Error", { description: ErrorMessage(error) });
    } finally {
      setLoadingShared(false);
    }
  };

  useEffect(() => {
    fetchShared();
  }, []);

  if (loadingShared)
    return (
      <div className="flex items-center justify-center gap-2 font-semibold min-h-[70vh]">
        <Loader className="animate-spin" /> Loading Projects
      </div>
    );

  return (
    <div className="flex flex-col gap-6 relative">
      <div className="flex flex-col items-start">
        <h1 className="text-2xl font-semibold dark:text-primary backdrop-blur-lg">
          Shared
        </h1>
        <p className="text-base font-normal text-muted-foreground">
          All your shared presentations
        </p>
      </div>

      {allShared.length > 0 ? (
        <Projects projects={allShared} />
      ) : (
        <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-8">
          <Projector className="size-32" />
          <div className="flex flex-col items-center justify-center text-center">
            <p className="text-3xl font-semibold text-primary">
              Nothing to see here
            </p>
            <p className="text-base font-normal text-muted-foreground">
              So here is a random image generated by{" "}
              <span className="text-ufo">Creative AI</span>
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
