import { Projector } from "lucide-react";
import React from "react";
import Projects from "./Components/Dashboard/Projects";

export default function DashboardPage() {
  const allProjects = ["llll"];
  return (
    <div className="w-full flex flex-col gap-6 relative">
      <div className="flex flex-col-reverse items-start w-full gap-6 sm:flex-row sm:justify-between sm:items-center">
        <div className="flex flex-col item-start">
          <h1 className="text-2xl font-semibold dark:text-primary backdrop-blur-lg">
            Projects
          </h1>
          <p className="text-base font-normal text-muted-foreground">
            All of your work in one place
          </p>
        </div>
      </div>

      {/* Projects */}
      {allProjects.length !== 0 ? (
        <Projects projects={allProjects} />
      ) : (
        <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-8">
          <Projector className="size-32" />
          <div className="flex flex-col items-center justify-center text-center">
            <p className="text-3xl font-semibold text-primary">
              Nothing to see here
            </p>
            <p className="text-base font-normal text-muted-foreground">
              So here is a random image generated by{" "}
              <span className="text-ufo">Creative AI</span>
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
