import React from "react";
import Projects from "../Components/Dashboard/Projects";
import DeleteAllButton from "./_components/DeleteAllButton";
import { Projector } from "lucide-react";

export default function Trash() {
  return (
    <div className="flex flex-col gap-6 relative">
      <div className="flex justify-between items-center">
        <div className="flex flex-col items-start">
          <h1 className="text-2xl font-semibold dark:text-primary backdrop-blur-lg">
            Trash
          </h1>
          <p className="text-base font-normal text-muted-foreground">
            All your deleted presentations
          </p>
        </div>
        <DeleteAllButton Projects={[]} />
      </div>

      {[].length > 0 ? (
        <Projects projects={[]} />
      ) : (
        <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-8">
          <Projector className="size-32" />
          <div className="flex flex-col items-center justify-center text-center">
            <p className="text-3xl font-semibold text-primary">
              Nothing to see here
            </p>
            <p className="text-base font-normal text-muted-foreground">
              So here is a random image generated by{" "}
              <span className="text-ufo">Creative AI</span>
            </p>
          </div>
        </div>
      )}
    </div>
  );
}
